name: Running Job (Container)
on:
  push:
    branches:
      - main
      - dev
env:
  CACHE_KEY: node-deps
  MONGODB_DB_NAME: gha-demo
#We run this test job on a Docker Container. We add container in a job defintion.
#We put all steps into a container by using some basic image, base environment to see how it works.
#We need to specify the name of the image that will be used. 
#All Docker Containers are based on some image
#It runs on the ubuntu machine, but it will just host the image, but this step does not have access to these tools
jobs:
  test:
    environment: testing
    runs-on: ubuntu-latest
    container: 
      image: node:18
    env:
      MONGODB_CONNECTION_PROTOCOL: mongodb+srv
      MONGODB_CLUSTER_ADDRESS: cluster0.ijn0koz.mongodb.net
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT # requires MongoDB Atlas to accept requests from anywhere!
#      - name: Run tests
#        run: npm test
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        env:
          PORT: 3000
        run: |        
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
          echo "${{ env.PORT }}"

#On the GitHub Actions in this workflow, you can see a step -> Initialize Containers
#It performs all all steps that were executed inside of this container
#We technically run all these steps in different environments.
#It is helpful if you need full control over the environment where you run your jobs